Return an emtpy list when files not found
hrehfeld/consult-xdg-recent-files pull request #1
Opened 2022-11-08 16:55 UTC by daanturo

(For consult-xdg-recent-files--xdg-recent-file-list and consult-xdg-recent-files--recent-system-files), otherwise abbreviate-file-name will iterate through a list of characters returned by message -> error.

2022-12-02 21:42 UTC, hrehfeld requested changes

2022-12-02 21:42 UTC, hrehfeld commented on consult-xdg-recent-files.el
> +      '())))
Can you replace `'()` with `nil`?

2022-12-02 21:42 UTC, hrehfeld commented on consult-xdg-recent-files.el
> +     '())))
Again, please prefer `nil`

2022-12-03 16:33 UTC, daanturo commented
> Can you replace '() with nil?

Done, it was just my personal convention to distinguish empty lists with `null` and/or `false`.

2022-12-05 09:53 UTC, hrehfeld commented
Thanks!

2022-12-05 09:54 UTC, merged